version: '3.4'

services:
  deltatre.presentation.api:
    image: ${DOCKER_REGISTRY-}deltatrepresentationapi
    build:
      context: .
      dockerfile: DeltaTre.Presentation.Api/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development